/*
 * Copyright 1999-2004 Carnegie Mellon University.  
 * Portions Copyright 2002-2004 Sun Microsystems, Inc.  
 * Portions Copyright 2002-2004 Mitsubishi Electric Research Laboratories.
 * All Rights Reserved.  Use is subject to license terms.
 * 
 * See the file "license.terms" for information on usage and
 * redistribution of this file, and for a DISCLAIMER OF ALL 
 * WARRANTIES.
 *
 */
package cclo;

import edu.cmu.sphinx.frontend.BaseDataProcessor;
import edu.cmu.sphinx.frontend.Data;
import edu.cmu.sphinx.frontend.DataProcessingException;
import edu.cmu.sphinx.frontend.DoubleData;
import edu.cmu.sphinx.util.Complex;
import edu.cmu.sphinx.util.props.*;
import java.awt.BorderLayout;
import java.awt.Canvas;
import java.awt.Color;
import java.awt.Frame;
import java.awt.Graphics;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.*;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import net.sf.json.JSONArray;
import net.sf.json.JSONObject;

/**
 * Computes the Discrete Fourier Transform (FT) of an input sequence, using Fast
 * Fourier Transform (FFT). Fourier Transform is the process of analyzing a
 * signal into its frequency components. In speech, rather than analyzing the
 * signal over its entire duration, we analyze one <b>window</b> of audio data.
 * This window is the product of applying a sliding Hamming window to the
 * signal. Moreover, since the amplitude is a lot more important than the phase
 * for speech recognition, this class returns the power spectrum of that window
 * of data instead of the complex spectrum. Each value in the returned spectrum
 * represents the strength of that particular frequency for that window of data.
 * <p/>
 * By default, the number of FFT points is the closest power of 2 that is equal
 * to or larger than the number of samples in the incoming window of data. The
 * FFT points can also be set by the user with the property defined by {@link
 * #PROP_NUMBER_FFT_POINTS}. The length of the returned power spectrum is the
 * number of FFT points, divided by 2, plus 1. Since the input signal is real,
 * the FFT is symmetric, and the information contained in the whole vector is
 * already present in its first half.
 * <p/>
 * Note that each call to {@link #getData() getData} only returns the spectrum
 * of one window of data. To display the spectrogram of the entire original
 * audio, one has to collect all the spectra from all the windows generated from
 * the original data. A spectrogram is a two dimensional representation of three
 * dimensional information. The horizontal axis represents time. The vertical
 * axis represents the frequency. If we slice the spectrogram at a given time,
 * we get the spectrum computed as the short term Fourier transform of the
 * signal windowed around that time stamp. The intensity of the spectrum for
 * each time frame is given by the color in the graph, or by the darkness in a
 * gray scale plot. The spectrogram can be thought of as a view from the top of
 * a surface generated by concatenating the spectral vectors obtained from the
 * windowed signal.
 * <p/>
 * For example, Figure 1 below shows the audio signal of the utterance "one
 * three nine oh", and Figure 2 shows its spectrogram, produced by putting
 * together all the spectra returned by this FFT. Frequency is on the vertical
 * axis, and time is on the horizontal axis. The darkness of the shade
 * represents the strength of that frequency at that point in time:
 * <p>
 * <br><img
 * src="doc-files/139o.jpg"> <br><b>Figure 1: The audio signal of the utterance
 * "one three nine oh".</b>
 * <p>
 * <br><img src="doc-files/139ospectrum.jpg">
 * <br><b>Figure 2: The spectrogram of the utterance "one three nine oh" in
 * Figure 1.</b>
 */
public class DiscreteFourierTransform extends BaseDataProcessor implements Share {

    final int FFTNo = 1024;
    static int ratio = 0;
    /**
     * The property for the number of points in the Fourier Transform.
     */
    @S4Integer(defaultValue = -1)
    public static final String PROP_NUMBER_FFT_POINTS = "numberFftPoints";
    /**
     * The property for the invert transform.
     */
    @S4Boolean(defaultValue = false)
    public static final String PROP_INVERT = "invert";
    private boolean isNumberFftPointsSet;
    private int numberFftPoints;
    private int logBase2NumberFftPoints;
    private int numberDataPoints;
    private boolean invert;
    private Complex[] weightFft;
    private Complex[] inputFrame;
    private Complex[] from;
    private Complex[] to;
    private Complex weightFftTimesFrom2;
    private Complex tempComplex;

    public DiscreteFourierTransform(int numberFftPoints, boolean invert) {

        initLogger();
        this.numberFftPoints = numberFftPoints;
        this.isNumberFftPointsSet = (numberFftPoints != -1);
        this.invert = invert;
    }

    public DiscreteFourierTransform() {
    }

    /*
     * (non-Javadoc)
     *
     * @see
     * edu.cmu.sphinx.util.props.Configurable#newProperties(edu.cmu.sphinx.util.props.PropertySheet)
     */
    ActionListener hisTimerHandler = new ActionListener() {

        @Override
        public void actionPerformed(ActionEvent e) {
        }
    };

    @Override
    public void newProperties(PropertySheet ps) throws PropertyException {
        super.newProperties(ps);
        logger = ps.getLogger();
        numberFftPoints = ps.getInt(PROP_NUMBER_FFT_POINTS);
        isNumberFftPointsSet = (numberFftPoints != -1);
        invert = ps.getBoolean(PROP_INVERT);
    }


    /*
     * (non-Javadoc) @see
     * edu.cmu.sphinx.frontend.DataProcessor#initialize(edu.cmu.sphinx.frontend.CommonConfig)
     */
    @Override
    public void initialize() {
        super.initialize();
        if (isNumberFftPointsSet) {
            initializeFFT();
        }
    }

    /**
     * Initialize all the data structures necessary for computing FFT.
     */
    private void initializeFFT() {
        /**
         * Number of points in the FFT. By default, the value is 512, which
         * means that we compute 512 values around a circle in the complex
         * plane. Complex conjugate pairs will yield the same power, therefore
         * the power produced by indices 256 through 511 are symmetrical with
         * the ones between 1 and 254. Therefore, we need only return values
         * between 0 and 255.
         */
        computeLogBase2(numberFftPoints);
        createWeightFft(numberFftPoints, invert);
        initComplexArrays();
        weightFftTimesFrom2 = new Complex();
        tempComplex = new Complex();
    }

    /**
     * Initialize all the Complex arrays that will be necessary for FFT.
     */
    private void initComplexArrays() {

        inputFrame = new Complex[numberFftPoints];
        from = new Complex[numberFftPoints];
        to = new Complex[numberFftPoints];

        for (int i = 0; i < numberFftPoints; i++) {
            inputFrame[i] = new Complex();
            from[i] = new Complex();
            to[i] = new Complex();
        }
    }

    /**
     * Process data, creating the power spectrum from an input frame.
     *
     * @param input the input frame
     * @return a DoubleData that is the power spectrum of the input frame
     * @throws java.lang.IllegalArgumentException
     *
     */
    private DoubleData process(DoubleData input)
            throws IllegalArgumentException {

        /**
         * Create complex input sequence equivalent to the real input sequence.
         * If the number of points is less than the window size, we incur in
         * aliasing. If it's greater, we pad the input sequence with zeros.
         */
        double[] in = input.getValues();

        if (numberFftPoints < in.length) {
            int i = 0;
            for (; i < numberFftPoints; i++) {
                inputFrame[i].set(in[i], 0.0f);
            }
            for (; i < in.length; i++) {
                tempComplex.set(in[i], 0.0f);
                inputFrame[i % numberFftPoints].addComplex(inputFrame[i % numberFftPoints], tempComplex);
            }
        } else {
            int i = 0;
            for (; i < in.length; i++) {
                inputFrame[i].set(in[i], 0.0f);
            }
            for (; i < numberFftPoints; i++) {
                inputFrame[i].reset();
            }
        }

        /**
         * Create output sequence.
         */
        double[] outputSpectrum = new double[(numberFftPoints >> 1) + 1];

        /**
         * Start Fast Fourier Transform recursion
         */
        recurseFft(inputFrame, outputSpectrum, numberFftPoints, invert);

        /**
         * Return the power spectrum
         */
        DoubleData output = new DoubleData(outputSpectrum, input.getSampleRate(),
                input.getCollectTime(),
                input.getFirstSampleNumber());

        return output;
    }

    /**
     * Make sure the number of points in the FFT is a power of 2 by computing
     * its log base 2 and checking for remainders.
     *
     * @param numberFftPoints number of points in the FFT
     * @throws java.lang.IllegalArgumentException
     *
     */
    private void computeLogBase2(int numberFftPoints)
            throws IllegalArgumentException {
        this.logBase2NumberFftPoints = 0;
        for (int k = numberFftPoints; k > 1;
                k >>= 1, this.logBase2NumberFftPoints++) {
            if (((k % 2) != 0) || (numberFftPoints < 0)) {
                throw new IllegalArgumentException("Not a power of 2: "
                        + numberFftPoints);
            }
        }
    }

    /**
     * Initializes the <b>weightFft[]</b> vector.
     * <p>
     * <b>weightFft[k] = w ^ k</b></p> where:
     * <p>
     * <b>w = exp(-2 * PI * i / N)</b></p>
     * <p>
     * <b>i</b> is a complex number such that <b>i * i = -1</b> and <b>N</b> is
     * the number of points in the FFT. Since <b>w</b> is complex, this is the
     * same as</p>
     * <p>
     * <b>Re(weightFft[k]) = cos ( -2 * PI * k / N)</b></p>
     * <p>
     * <b>Im(weightFft[k]) = sin ( -2 * PI * k / N)</b></p>
     *
     * @param numberFftPoints number of points in the FFT
     * @param invert whether it's direct (false) or inverse (true) FFT
     */
    private void createWeightFft(int numberFftPoints, boolean invert) {
        /**
         * weightFFT will have numberFftPoints/2 complex elements.
         */
        weightFft = new Complex[numberFftPoints >> 1];

        /**
         * For the inverse FFT, w = 2 * PI / numberFftPoints;
         */
        double w = -2 * Math.PI / numberFftPoints;
        if (invert) {
            w = -w;
        }

        for (int k = 0; k < (numberFftPoints >> 1); k++) {
            weightFft[k] = new Complex(Math.cos(w * k), Math.sin(w * k));
        }
    }

    /**
     * Reads the next DoubleData object, which is a data frame from which we'll
     * compute the power spectrum. Signal objects just pass through unmodified.
     *
     * @return the next available power spectrum DoubleData object, or null if
     * no Spectrum object is available
     * @throws DataProcessingException if there is a processing error
     */
    @Override
    public Data getData() throws DataProcessingException {

        Data input = getPredecessor().getData();

        getTimer().start();

        if ((input != null) && (input instanceof DoubleData)) {
            DoubleData data = (DoubleData) input;
            if (!isNumberFftPointsSet) {
                /*
                 * If numberFftPoints is not set by the user, figure out the
                 * numberFftPoints and initialize the data structures
                 * appropriately.
                 */
                if (numberDataPoints != data.getValues().length) {
                    numberDataPoints = data.getValues().length;
                    numberFftPoints = getNumberFftPoints(numberDataPoints);
                    initializeFFT();
                }
            } else {
                /*
                 * Warn if the user-set numberFftPoints is not ideal.
                 */
                if (numberDataPoints != data.getValues().length) {
                    numberDataPoints = data.getValues().length;
                    int idealFftPoints = getNumberFftPoints(numberDataPoints);
                    if (idealFftPoints != numberFftPoints) {
                        logger.warning("User set numberFftPoints ("
                                + numberFftPoints + ") is not ideal ("
                                + idealFftPoints + ')');
                    }
                }
            }

            input = process(data);
            //*************** grab the output of FFT by cclo / every 0.01 sec FFTNo double frequency data ********************
            DoubleData output = (DoubleData) input;
            double cc[] = output.getValues();
            voice_Process(cc);
            //getVoid2(cc);

        }

        // At this point - or in the call immediatelly preceding
        // this -, we should have created a cepstrum frame with
        // whatever data came last, even if we had less than
        // window size of data.
        getTimer().stop();

        return input;
    }

    /**
     * Returns the ideal number of FFT points given the number of samples. The
     * ideal number of FFT points is the closest power of 2 that is equal to or
     * larger than the number of samples in the incoming window.
     *
     * @param numberSamples the number of samples in the incoming window
     * @return the closest power of 2 that is equal to or larger than the number
     * of samples in the incoming window
     */
    private static int getNumberFftPoints(int numberSamples) {
        int fftPoints = 1;

        while (fftPoints < numberSamples) {
            fftPoints <<= 1;
            if (fftPoints < 1) {
                throw new Error("Invalid # of FFT points: " + fftPoints);
            }
        }
        return fftPoints;
    }

    /**
     * Establish the recursion. The FFT computation will be computed by as a
     * recursion. Each stage in the butterfly will be fully computed during
     * recursion. In fact, we use the mechanism of recursion only because it's
     * the simplest way of switching the "input" and "output" vectors. The
     * output of a stage is the input to the next stage. The butterfly computes
     * elements in place, but we still need to switch the vectors. We could copy
     * it (not very efficient...) or, in C, switch the pointers. We can avoid
     * the pointers by using recursion.
     *
     * @param input input sequence
     * @param output output sequence
     * @param numberFftPoints number of points in the FFT
     * @param invert whether it's direct (false) or inverse (true) FFT
     */
    private void recurseFft(Complex[] input,
            double[] output,
            int numberFftPoints,
            boolean invert) {

        double divisor;

        /**
         * The direct and inverse FFT are essentially the same algorithm, except
         * for two difference: a scaling factor of "numberFftPoints" and the
         * signal of the exponent in the weightFft vectors, defined in the
         * method <code>createWeightFft</code>.
         */
        if (!invert) {
            divisor = 1.0;
        } else {
            divisor = (double) numberFftPoints;
        }

        /**
         * Initialize the "from" and "to" variables.
         */
        for (int i = 0; i < numberFftPoints; i++) {
            to[i].reset();
            from[i].scaleComplex(input[i], divisor);
        }

        /**
         * Repeat the recursion log2(numberFftPoints) times, i.e., we have
         * log2(numberFftPoints) butterfly stages.
         */
        butterflyStage(from, to, numberFftPoints, numberFftPoints >> 1);

        /**
         * Compute energy ("float") for each frequency point from the fft
         * ("complex")
         */
        if ((this.logBase2NumberFftPoints & 1) == 0) {
            for (int i = 0; i <= (numberFftPoints >> 1); i++) {
                output[i] = from[i].squaredMagnitudeComplex();
            }
        } else {
            for (int i = 0; i <= (numberFftPoints >> 1); i++) {
                output[i] = to[i].squaredMagnitudeComplex();
            }
        }
    }

    /**
     * Compute one stage in the FFT butterfly. The name "butterfly" appears
     * because this method computes elements in pairs, and a flowgraph of the
     * computation (output "0" comes from input "0" and "1" and output "1" comes
     * from input "0" and "1") resembles a butterfly.
     * <p/>
     * We repeat <code>butterflyStage</code> for <b>log_2(numberFftPoints)</b>
     * stages, by calling the recursion with the argument
     * <code>currentDistance</code> divided by 2 at each call, and checking if
     * it's still > 0.
     *
     * @param from the input sequence at each stage
     * @param to the output sequence
     * @param numberFftPoints the total number of points
     * @param currentDistance the "distance" between elements in the butterfly
     */
    private void butterflyStage(Complex[] from,
            Complex[] to,
            int numberFftPoints,
            int currentDistance) {
        int ndx1From;
        int ndx2From;
        int ndx1To;
        int ndx2To;
        int ndxWeightFft;

        if (currentDistance > 0) {

            int twiceCurrentDistance = 2 * currentDistance;

            for (int s = 0; s < currentDistance; s++) {
                ndx1From = s;
                ndx2From = s + currentDistance;
                ndx1To = s;
                ndx2To = s + (numberFftPoints >> 1);
                ndxWeightFft = 0;
                while (ndxWeightFft < (numberFftPoints >> 1)) {
                    /**
                     * <b>weightFftTimesFrom2 = weightFft[k] </b> <b>
                     * *from[ndx2From]</b>
                     */
                    weightFftTimesFrom2.multiplyComplex(weightFft[ndxWeightFft], from[ndx2From]);
                    /**
                     * <b>to[ndx1To] = from[ndx1From] </b> <b> +
                     * weightFftTimesFrom2</b>
                     */
                    to[ndx1To].addComplex(from[ndx1From], weightFftTimesFrom2);
                    /**
                     * <b>to[ndx2To] = from[ndx1From] </b> <b> -
                     * weightFftTimesFrom2</b>
                     */
                    to[ndx2To].subtractComplex(from[ndx1From], weightFftTimesFrom2);
                    ndx1From += twiceCurrentDistance;
                    ndx2From += twiceCurrentDistance;
                    ndx1To += currentDistance;
                    ndx2To += currentDistance;
                    ndxWeightFft += currentDistance;
                }
            }

            /**
             * This call'd better be the last call in this block, so when it
             * returns we go straight into the return line below.
             *
             * We switch the <i>to</i> and <i>from</i> variables, the total
             * number of points remains the same, and the <i>currentDistance</i>
             * is divided by 2.
             */
            butterflyStage(to, from, numberFftPoints, (currentDistance >> 1));
        }
    }
    //**************************************************************************
    Main pMain;
    double shortVec[] = new double[FFTNo];
    double featureFreq[] = new double[FFTNo];
    int iter5 = 0;
    int iter500 = 0;
    boolean silent = false;
    double SPEC_RATIO = 1.1;
    double DecayRate = 0.996;
    double peakAvg = 0.0;
    double specSum = 0.0, avgSpecSum = 0.09, avgSpecMag = 100.0, minSpecSum = Double.MAX_VALUE;
    int count = 0;
    int pkNo = 5;
    boolean stable = false;

    /*public void getBaby(double voice[]) {
       
        int peakIdx[] = new int[pkNo];
        double peakValue[] = new double[pkNo];
        boolean isPeak[] = new boolean[FFTNo];

        specSum = 0.0;

        for (int i = 0; i < FFTNo; i++) {
            isPeak[i] = true;
        }

        double ratio;
        for (int i = 0; i < FFTNo; i++) {
            shortVec[i] = shortVec[i] * 0.95 + voice[i] * 0.05; // short pattern
            specSum += shortVec[i];
        }
        if (specSum < minSpecSum) {
            minSpecSum = specSum;
        }
        avgSpecMag = specSum / (double) FFTNo;

        for (int i = 0; i < FFTNo; i++) {
            featureFreq[i] = Math.log10(shortVec[i]);
            // featureFreq[i] = shortVec[i];
        }
        pMain.freqFr.updateSpec(featureFreq);

        peakIdx[0] = -1;
        peakValue[0] = Double.MIN_VALUE;

        int low = 1, up;
        int cut = 5;
        int firstPeak = -1;
        boolean isFirstPeak = true;
        int leftOff = 5, rightOff = 5;
        for (int i = 0; i < FFTNo; i++) {
            if (i < cut) {
                isPeak[i] = false;
                continue;
            }
            if (isFirstPeak) {
                low = (i < cut ? cut : low);
                up = i + i - 3;

                if (up > FFTNo - 1) {
                    up = FFTNo - 1;
                }
            } else {
                low = i - leftOff;
                up = i + rightOff;
                if (up > FFTNo - 1) {
                    up = FFTNo - 1;
                }
            }

            for (int j = low; j <= up; j++) {
                if (featureFreq[i] < featureFreq[j]) {
                    isPeak[i] = false;
                    break;
                }
            }

            if (isPeak[i]) {
                if (isFirstPeak) {
                    leftOff = i - 3;
                    rightOff = i - 3;
                    isFirstPeak = false;
                }
                if (featureFreq[i] > peakValue[0]) {
                    peakIdx[0] = i;
                    peakValue[0] = featureFreq[i];
                }
            }
        }

        pMain.freqFr.updateSpec(featureFreq);
        peakAvg = peakAvg * 0.996 + peakValue[0] * 0.004;
        avgSpecSum = avgSpecSum * DecayRate + specSum * (1.0 - DecayRate);
        avgSpecMag = avgSpecSum / (double) FFTNo;
        if (count == 0) {
            // System.out.print("\nPeak Avg: " + peakAvg);
            // System.out.print("\nSpecSum Avg: " + avgSpecSum);
        }
        count = (++count) % 1000;
        int val = 0;
        if (specSum > minSpecSum * SPEC_RATIO) { // && specSum > 1.001 * avgSpecSum) { // && specSum > 9020.0) {
            silent = false;

            for (int i = 0; i < FFTNo; i++) {
                if (isPeak[i]) { // // && shortVec[i] > avgSpecMag * 1.0) {
                    val = 1;
                    // System.out.print(" " + i);
                } else {
                    isPeak[i] = false;
                    val = 0;
                }
                // pMain.specFr.wChart2.updateSeries(i, val);
            }
            pMain.scorer.matchLevel(isPeak);

        } else {
            if (!silent) {
                // System.out.print("\nS ");
                pMain.scorer.resetLevel();
                silent = true;
                pMain.scorer.resetLevel();
            }
//            stable = true;
//            DecayRate = 0.996;
            pMain.freqFr.updateSpec(featureFreq);
        }
        if (pMain.scorer.tFileState == STATE.RECORDING) {
//                if (++iter500 % 50 == 0) {
//                    System.out.printf(".");
//                    iter500 = 1;
//                    for (int i = 0; i < FFTNo; i++) {
//                        pMain.scorer.addData(i, 0.0);
//                    }
//                } else {
//                    return;
//                }
        } else if (pMain.scorer.latState == STATE.MATCH) {
//            if (++iter500 % 500 == 0) {
//                IncNode iNode = new IncNode();
//                iter500 = 1;
//                for (int i = 0; i < FFTNo; i++) {
//                    iNode.add(i, featureFreq[i]);
//                }
//                // pMain.scorer.addMatchInput(iNode);
//            } else {
//                return;
//            }
        }
    }*/
    public void setShortDiffAvg(double shortDiffAvg_) {
    }

    public void setMagThresh(double magThresh_) {
        SPEC_RATIO = magThresh_;
        // System.out.println("\nMag_Thresh: " + SPEC_RATIO);
    }

    public void setAED(Main aed_) {
        pMain = aed_;
    }

    /*public void getVoid(double voice[]) {//voice[1024]輸入

        specSum = 0.0;
        for (int i = 0; i < FFTNo; i++) {
            shortVec[i] = shortVec[i] * 0.95 + voice[i] * 0.05; // short pattern
            specSum += shortVec[i];
        }
        if (specSum < minSpecSum) {
            minSpecSum = specSum;
        }
        avgSpecMag = specSum / (double) FFTNo;
        for (int i = 0; i < FFTNo; i++) {
            featureFreq[i] = Math.log10(shortVec[i]);
        }
        pMain.freqFr.updateSpec(featureFreq);
        //-------------------------------------------------------------------------//上面套用老師寫的
        double tempFreq[] = new double[FFTNo];//暫存頻率
        double characterFreqMax[] = new double[128];//最大頻率
        double characterFreq[] = new double[128];//特徵頻率
        System.arraycopy(featureFreq, 0, tempFreq, 0, featureFreq.length);//把特徵陣列(老師)複製到暫存陣列裡
        int j = 0;
        for (int i = 0; i < FFTNo; i += 8) {
            characterFreq[j] = (tempFreq[i] + tempFreq[i + 1] + tempFreq[i + 2] + tempFreq[i + 3]
                    + tempFreq[i + 1] + tempFreq[i + 4] + tempFreq[i + 5] + tempFreq[i + 6]) / 8;//將暫存陣列平均存到特徵陣列(我)裡 以8個為一單位
            j++;
        }
        System.arraycopy(characterFreq, 0, characterFreqMax, 0, characterFreq.length);//將特徵陣列(我)複製到最大特徵陣列(我)裡
        Arrays.sort(characterFreqMax);//排序找出最大
        double maxFreq = characterFreqMax[127];//將最大值儲存到maxFreq
        System.out.println(maxFreq);
        int characterIndex = 0;
        for (int i = 0; i < 128; i++) {//找出此maxFreq的index值
            if (characterFreq[i] == maxFreq) {
                characterIndex = i;
                break;
            }
        }
        char chPrint[] = new char[128]; //儲存星號陣列

        for (int i = 0; i < 128; i++) {//畫出星號所在位置
            if (i != characterIndex) {
                chPrint[i] = ' ';
            } else {
                chPrint[i] = '*';
            }
        }
        String temp = Arrays.toString(chPrint);

        // testframe putdata = new testframe();
        pMain.tFrame.putdata(temp);
        System.out.println(Arrays.toString(chPrint));
    }*/
    public void getVoid2(double voice[]) {

        int peakIdx[] = new int[pkNo];
        double peakValue[] = new double[pkNo];
        boolean isPeak[] = new boolean[FFTNo];

        specSum = 0.0;

        for (int i = 0; i < FFTNo; i++) {
            isPeak[i] = true;
        }

        double ratio;
        for (int i = 0; i < FFTNo; i++) {
            shortVec[i] = shortVec[i] * 0.5 + voice[i] * 0.5; // short pattern
            specSum += shortVec[i];
        }
        if (specSum < minSpecSum) {
            minSpecSum = specSum;
        }
        avgSpecMag = specSum / (double) FFTNo;

        for (int i = 0; i < FFTNo; i++) {
            featureFreq[i] = Math.log10(shortVec[i]);
            // featureFreq[i] = shortVec[i];
        }
        pMain.freqFr.updateSpec(featureFreq);

        peakIdx[0] = -1;
        peakValue[0] = Double.MIN_VALUE;

        int low = 1, up;
        int cut = 5;
        int firstPeak = -1;
        boolean isFirstPeak = true;
        int leftOff = 5, rightOff = 5;
        for (int i = 0; i < FFTNo; i++) {
            if (i < cut) {
                isPeak[i] = false;
                continue;
            }
            if (isFirstPeak) {
                low = (i < cut ? cut : low);
                up = i + i - 3;

                if (up > FFTNo - 1) {
                    up = FFTNo - 1;
                }
            } else {
                low = i - leftOff;
                up = i + rightOff;
                if (up > FFTNo - 1) {
                    up = FFTNo - 1;
                }
            }

            for (int j = low; j <= up; j++) {
                if (featureFreq[i] < featureFreq[j]) {
                    isPeak[i] = false;
                    break;
                }
            }

            if (isPeak[i]) {
                if (isFirstPeak) {
                    leftOff = i - 3;
                    rightOff = i - 3;
                    isFirstPeak = false;
                }
                if (featureFreq[i] > peakValue[0]) {
                    peakIdx[0] = i;
                    peakValue[0] = featureFreq[i];
                }
            }
        }

        pMain.freqFr.updateSpec(featureFreq);
        peakAvg = peakAvg * 0.96 + peakValue[0] * 0.04;
        avgSpecSum = avgSpecSum * DecayRate + specSum * (1.0 - DecayRate);
        avgSpecMag = avgSpecSum / (double) FFTNo;
        if (count == 0) {
            // System.out.print("\nPeak Avg: " + peakAvg);
            // System.out.print("\nSpecSum Avg: " + avgSpecSum);
        }
        count = (++count) % 1000;
        int val = 0;
        if (specSum > minSpecSum * SPEC_RATIO) { // && specSum > 1.001 * avgSpecSum) { // && specSum > 9020.0) {
            silent = false;

            for (int i = 0; i < FFTNo; i++) {
                if (isPeak[i]) { // // && shortVec[i] > avgSpecMag * 1.0) {
                    val = 1;
                    // System.out.print(" " + i);
                } else {
                    isPeak[i] = false;
                    val = 0;
                }
                // pMain.specFr.wChart2.updateSeries(i, val);
            }
            pMain.scorer.matchLevel(isPeak);

        } else {
            if (!silent) {
                // System.out.print("\nS ");
                pMain.scorer.resetLevel();
                silent = true;
                pMain.scorer.resetLevel();
            }
//            stable = true;
//            DecayRate = 0.996;
            pMain.freqFr.updateSpec(featureFreq);
        }
        //----------------------------------------------------------------------
        //getPeak1(featureFreq);
        //getPeak2(featureFreq);
        getPeak2_New(featureFreq);
        //----------------------------------------------------------------------
        double max = 0;
        double min = 99999;
        for (int i = 0; i < FFTNo; i++) {//找出最大最小值
            if (max < featureFreq[i]) {
                max = featureFreq[i];
            }
            if (min > featureFreq[i]) {
                min = featureFreq[i];
            }
        }
        double encode = max - min; //取最大值最小值的區間
        int encodeFreq[] = new int[FFTNo];
        for (int i = 0; i < FFTNo; i++) {
            encodeFreq[i] = (int) ((featureFreq[i] - min) * (255 / encode)); //對每個頻率進行編碼(0~255)
        }

        // System.out.println("pudata");
        pMain.tFrame.putdata(encodeFreq);
        //----------------------------------------------------------------------

    }

//    public void getPeak1(double featureFreq[]) {//可取到重點波峰，資料處理速度快
//        Queue<Integer> isPeak = new LinkedList<>();
//        Queue<Double> isPeakValue = new LinkedList<>();
//        int peakNo = 0;
//        while ((peakNo + 4) <= featureFreq.length) {
//            double peak[] = new double[8];
//            System.arraycopy(featureFreq, peakNo, peak, 0, 8);//區間取樣，將區間複製到peak陣列裡(來源陣列，來源起始索引，目的陣列，目的起始索引，複製長度)
//            double max = 0;
//            int maxIndex = 0;
//            for (int i = 0; i < 8; i++) {//找出最大值
//                if (max < peak[i]) {
//                    max = peak[i];
//                    maxIndex = i + peakNo; //存儲最大值的索引
//                }
//            }
//            if (max != 0 && (maxIndex == peakNo || maxIndex == peakNo + 8)) {//當若最大值不是在區間取樣的邊線時，則為波峰
//                break;
//            } else {
//                if (isPeak.contains(maxIndex)) {
//                    break;
//                } else {
//                    isPeak.offer(maxIndex);//將波峰放入佇列中
//                    isPeakValue.offer(featureFreq[maxIndex]);//將波峰值放入佇列中
//                }
//            }
//            peakNo += 4;
//        }
//        System.out.println(isPeak.toString());
//        //System.out.println(isPeakValue.toString());
//        //----------------------------------------------------------------------
//        Queue<Double> realPeak = new LinkedList<>();
//        double d = 21.533203125;
//        for (int index : isPeak) {
//            int i = 1;
//            while (index * i <= 1024) {//確認是否有梵音
//                Integer sanskrit = (index * i); //梵音索引為倍數增長
//                /*if (index < 30 && i == 2) { //前面的區段，取到二個梵音就列入
//                    realPeak.offer(index * d);
//                } else if (index > 30 && i == 3) { //後面的區段，若成功找到三個梵音一樣為波峰，就將它列入
//                    realPeak.offer(index * d);
//                }*/
//                if (i == 2) {
//                    realPeak.offer(index * d);
//                }
//                if (featureFreq[sanskrit] > featureFreq[sanskrit - 1] && featureFreq[sanskrit] > featureFreq[sanskrit + 1]) {
//                    i++;
//                } else {
//                    break;
//                }
//                /*if (isPeak.contains(sanskritlow)||isPeak.contains(sanskritup)) {
//                    i++;
//                } else {
//                    break;
//                }*/
//            }
//        }
//
//        System.out.println(realPeak.toString());
//        //----------------------------------------------------------------------
//        String sanskritArr[][] = { //將音階對照表列出，從0開始到5
//            {"16.35", "32.70", "65.41", "130.81", "261.63", "523.25", "C"},
//            {"17.32", "34.65", "69.30", "138.59", "277.18", "554.37", "C♯/D♭"},
//            {"18.35", "36.71", "73.42", "146.83", "293.66", "587.33", "D"},
//            {"19.45", "38.89", "77.78", "155.56", "311.13", "622.25", "D♯/E♭"},
//            {"20.60", "41.20", "82.41", "164.81", "329.63", "659.26", "E"},
//            {"21.83", "43.65", "87.31", "174.61", "349.23", "698.46", "F"},
//            {"23.12", "46.25", "92.50", "185.00", "369.99", "739.99", "F♯/G♭"},
//            {"24.50", "49.00", "98.00", "196.00", "392.00", "783.99", "G"},
//            {"25.96", "51.91", "103.83", "207.65", "415.30", "830.61", "G♯/A♭"},
//            {"27.50", "55.00", "110.00", "220.00", "440.00", "880.00", "A"},
//            {"29.14", "58.27", "116.54", "233.08", "466.16", "932.33", "A♯/B♭"},
//            {"30.87", "61.74", "123.47", "246.94", "493.88", "987.77", "B"}
//        };
//        while (!realPeak.isEmpty()) {
//            Double temp = realPeak.poll();
//            for (String arr[] : sanskritArr) { //逐列判斷是否有在這些區間
//                for (int i = 0; i < arr.length; i++) {
//                    if (i == 6) {
//                        break;
//                    }
//                    if (Math.floor(temp - i * 2) == Math.floor(Double.parseDouble(arr[i]))
//                            || (Math.floor(temp - i * 2) < Math.floor(Double.parseDouble(arr[i]))
//                            && Math.floor(Double.parseDouble(arr[i])) < Math.floor(temp + i * 2))) {//當i越大，容許誤差也越大
//                        System.out.println(arr[6] + "[" + i + "]");
//                    }
//                }
//            }
//        }
//    }
//    public void getPeak2(double featureFreq[]) { //取前面200個波峰
//        Queue<Integer> isPeak = new LinkedList<>();
//        double peak[] = new double[500];
//        System.arraycopy(featureFreq, 0, peak, 0, 500);//區間取樣，將區間複製到peak陣列裡(來源陣列，來源起始索引，目的陣列，目的起始索引，複製長度)
//        for (int i = 1; i < peak.length - 1; i++) {
//            if (peak[i] >= 6 && i >= 5) {
//                if (peak[i] > peak[i - 1] && peak[i] > peak[i + 1]) { //若當前的頻率比前後頻率都高，就把它視為波峰 
//                    isPeak.offer(i);
//                    //isPeakValue.offer(featureFreq[i]);
//                }
//            }
//        }
//        System.out.println(isPeak.toString());
//        //----------------------------------------------------------------------
//        String sanskritArr[][] = { //將音階對照表列出，從0開始到5
//            {"1.614", "3.193", "6.387", "12.774", "25.549", "51.098", "C"},
//            {"1.691", "3.383", "6.767", "13.534", "27.068", "54.137", "C♯/D♭"},
//            {"1.791", "3.584", "7.169", "14.338", "28.677", "57.356", "D"},
//            {"1.899", "3.797", "7.595", "15.191", "30.383", "60.766", "D♯/E♭"},
//            {"2.011", "4.023", "8.047", "16.094", "32.190", "64.380", "E"},
//            {"2.131", "4.262", "8.526", "17.051", "34.104", "68.208", "F"},
//            {"2.257", "4.516", "9.033", "18.066", "36.131", "72.264", "F♯/G♭"},
//            {"2.392", "4.785", "9.570", "19.140", "38.281", "76.561", "G"},
//            {"2.535", "5.069", "10.139", "20.278", "40.556", "81.114", "G♯/A♭"},
//            {"2.685", "5.371", "10.742", "21.484", "42.968", "85.937", "A"},
//            {"2.845", "5.690", "11.380", "22.761", "45.523", "91.047", "A♯/B♭"},
//            {"3.014", "6.029", "12.057", "24.115", "48.230", "96.461", "B"}
//        };
//        Queue<String> Peak = new LinkedList<>();
//        for (String arr[] : sanskritArr) {
//            for (int i = 0; i < arr.length; i++) {
//                if (i == 6) {
//                    break;
//                }
//                for (int j = 1; j <= 10; j++) {
//                    int count = 0;
//                    Integer check = (int) (Double.parseDouble(arr[i]) * j);
//                    if (isPeak.contains(check) || isPeak.contains(check + 1) || isPeak.contains(check - 1)) {
//                        count++;
//                    }
//                    if (count > 3) {
//                        System.out.println(arr[6] + "[" + i + "]");
//                        Peak.offer(arr[6] + "[" + i + "]");
//                        break;
//                    }
//                }
//            }
//        }
//        System.out.println(Peak.toString());
//    } 
    public void voice_Process(double voice[]) {
        for (int i = 0; i < FFTNo; i++) {
            shortVec[i] = shortVec[i] * 0.95 + voice[i] * 0.05; // short pattern
        }
        for (int i = 0; i < FFTNo; i++) {
            featureFreq[i] = Math.log10(shortVec[i]);
            // featureFreq[i] = shortVec[i];
        }
        pMain.freqFr.updateSpec(featureFreq);
        //----------------------------------------------------------------------
        getPeak2_New(featureFreq);
        //----------------------------------------------------------------------
    }

    public void getPeak2_New(double featureFreq[]) { //取前面200個波峰
        LinkedList<Integer> isPeak = new LinkedList<>();
        double peak[] = new double[500];
        System.arraycopy(featureFreq, 0, peak, 0, 500);//區間取樣，將區間複製到peak陣列裡(來源陣列，來源起始索引，目的陣列，目的起始索引，複製長度)
        for (int i = 1; i < peak.length - 1; i++) {
            if (peak[i] >= 7 && i >= 5) {
                if (peak[i] > peak[i - 1] && peak[i] > peak[i + 1]) { //若當前的頻率比前後頻率都高，就把它視為波峰 
                    isPeak.offer(i);
                    //isPeakValue.offer(featureFreq[i]);
                }
            }
        }
        System.out.println(isPeak.toString());
//        Integer[] temparr= isPeak.toArray(new Integer[isPeak.size()]);
        if (isPeak.size() >= 5) {
            int temparr[] = new int[isPeak.size()];
            for (int i = 0; i < isPeak.size(); i++) {
                temparr[i] = isPeak.get(i);
            }
            //System.out.println(temparr[0]);
            voice_Store(temparr);
        }
        //voice_Store(isPeak);
        //----------------------------------------------------------------------
        String sanskritArr[][] = { //將音階對照表列出，從0開始到5
            {"7", "14", "22", "29", "36", "43", "51", "58", "65", "72", "79", "87", "94", "101", "109", "D♯/E♭[3]"},
            {"8", "15", "23", "31", "38", "46", "54", "61", "69", "76", "84", "92", "99", "107", "115", "E[3]"},
            {"8", "16", "24", "32", "40", "48", "56", "65", "73", "81", "89", "97", "105", "113", "121", "F[3]"},
            {"9", "17", "26", "34", "43", "51", "60", "68", "77", "86", "94", "103", "111", "120", "129", "F♯/G♭[3]"},
            {"9", "18", "27", "36", "45", "54", "63", "72", "81", "91", "100", "109", "118", "127", "136", "G[3]"},
            {"10", "19", "29", "38", "48", "58", "67", "77", "86", "96", "106", "115", "125", "134", "144", "G♯/A♭[3]"},
            {"10", "20", "31", "41", "51", "61", "71", "82", "92", "102", "112", "122", "133", "143", "153", "A[3]"},
            {"11", "22", "32", "43", "54", "65", "75", "86", "97", "108", "118", "129", "140", "151", "162", "A♯/B♭[3]"},
            {"11", "23", "34", "46", "57", "69", "80", "92", "103", "115", "126", "138", "149", "161", "172", "B[3]"},
            {"12", "24", "36", "49", "61", "73", "85", "97", "109", "121", "133", "146", "158", "170", "182", "C[3]"},
            {"13", "26", "39", "52", "64", "77", "90", "103", "116", "129", "142", "155", "168", "181", "193", "C♯/D♭[3]"},
            {"14", "27", "41", "55", "69", "82", "96", "109", "123", "137", "151", "165", "178", "192", "206", "D[3]"},
            {"15", "29", "44", "58", "73", "87", "102", "116", "131", "145", "160", "174", "189", "203", "218", "D♯/E♭[4]"}
        };
        LinkedList<String> Peak = new LinkedList<>();
        for (String arr[] : sanskritArr) {
            int PeakCount = 0;
            for (int i = 0; i < arr.length; i++) {
                if (i == 15) {
                    break;
                }
                if (PeakCount > 10) {
                    Peak.offer(arr[15]);
                    break;
                }
                if (isPeak.contains(Integer.parseInt(arr[i]))) {
                    PeakCount++;
                }
            }
        }
        System.out.println(Peak.toString());
    }
    LinkedList<int[]> store = new LinkedList<>();

    public void voice_Store(int[] peak) {//用來儲存音樂特徵
        boolean opener=false;
        if (store.size() < 300) { //限制歌曲的儲存長度為300個波峰陣列
            store.offer(peak);
            if(store.size()==300){//若轉換完成，開啟存取DB開關
                opener=true;
            }
        } else {
            System.out.println("Music input time is too long!");
        }
        if(opener==true){ //若存取開關開啟
            //JSONArray jsonarray = JSONArray.fromObject(store);
            pMain.con.insert(store);//將資料寫入DB
            opener=false;
        }
//        int temparr[]=new int[store.size()];
//        for(int i=0;i<store.size();i++){
//            temparr[i]=store.get(i);
//        }
    }
    
    public void voice_Compare(int[] peak) {
        pMain.con.takeout();
    }

}
